CREATE DATABASE IF NOT EXISTS mst_database CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE mst_database;

CREATE TABLE users (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, first_name VARCHAR(80) NOT NULL, middle_name VARCHAR(80) NULL, last_name VARCHAR(80) NOT NULL, email VARCHAR(190) NOT NULL UNIQUE, username VARCHAR(40) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL, role ENUM('Super Admin','Admin','Tenant') NOT NULL DEFAULT 'Tenant', status ENUM('Active','Inactive','Suspended') NOT NULL DEFAULT 'Active', created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, last_login TIMESTAMP NULL, INDEX idx_users_role_status (role, status));
CREATE TABLE computers (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, device_id VARCHAR(40) NOT NULL UNIQUE, hostname VARCHAR(120) NOT NULL, ip_address VARCHAR(45) NOT NULL, operating_system VARCHAR(80) NOT NULL, status ENUM('online','offline','warning','threat') NOT NULL, threat_level ENUM('safe','unknown','warning','high') NOT NULL, cpu_usage TINYINT UNSIGNED NULL, memory_usage TINYINT UNSIGNED NULL, last_seen VARCHAR(40) NOT NULL, agent_status ENUM('connected','disconnected','outdated') NOT NULL, mac_address VARCHAR(17) NULL, agent_version VARCHAR(20) NULL, disk_usage TINYINT UNSIGNED NULL, last_heartbeat_at DATETIME NULL, agent_token_hash CHAR(64) NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE threats (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, computer_id INT UNSIGNED NULL, threat_name VARCHAR(160) NOT NULL, description TEXT NULL, severity ENUM('CRITICAL','HIGH','MEDIUM','LOW','SAFE') NOT NULL, status ENUM('Detected','Investigating','Quarantined','Resolved','Ignored') NOT NULL DEFAULT 'Detected', source VARCHAR(80) NOT NULL, detected_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, resolved_at TIMESTAMP NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, scan_id INT UNSIGNED NULL, INDEX idx_threat_status (status), INDEX idx_threat_severity (severity), CONSTRAINT fk_threat_computer FOREIGN KEY (computer_id) REFERENCES computers(id) ON DELETE SET NULL);
CREATE TABLE scans (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, computer_id INT UNSIGNED NULL, scan_type ENUM('File Scan','Quick Scan','Security Scan','Network Scan') NOT NULL, source ENUM('Agent','Auto','Upload') NOT NULL DEFAULT 'Agent', status ENUM('PENDING','SAFE','THREAT','WARNING','UNKNOWN','FAILED') NOT NULL, scan_state ENUM('Pending','Scanning','Completed','Failed') NOT NULL DEFAULT 'Pending', file_name VARCHAR(255) NULL, file_hash VARCHAR(255) NULL, threat_count SMALLINT UNSIGNED NOT NULL DEFAULT 0, started_at TIMESTAMP NULL, completed_at TIMESTAMP NULL, created_by INT UNSIGNED NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, duration VARCHAR(30) NULL, file_event_id BIGINT UNSIGNED NULL, file_path VARCHAR(1024) NULL, risk_level ENUM('Unknown','Safe','Low','Medium','High','Critical','Failed') NULL, scan_details TEXT NULL, detection VARCHAR(255) NULL, evidence_strength ENUM('Strong','Moderate','Limited','N/A') NULL, analysis_coverage ENUM('Full','Partial') NULL, scanner VARCHAR(255) NULL, file_size BIGINT UNSIGNED NULL, file_type VARCHAR(80) NULL, stored_file VARCHAR(80) NULL, stored_until DATETIME NULL, vt_analysis_id VARCHAR(160) NULL, vt_checked_at DATETIME NULL, CONSTRAINT fk_scan_computer FOREIGN KEY (computer_id) REFERENCES computers(id) ON DELETE SET NULL, CONSTRAINT fk_scan_creator FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL, INDEX idx_scans_status (status), INDEX idx_scans_state (scan_state), INDEX idx_scans_risk (risk_level), INDEX idx_scans_created (created_at), INDEX idx_scans_hash (file_hash(64)));
CREATE TABLE activity_logs (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id INT UNSIGNED NULL, action VARCHAR(60) NOT NULL, description VARCHAR(255) NULL, target_type VARCHAR(60) NULL, target_id VARCHAR(60) NULL, ip_address VARCHAR(45) NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT fk_activity_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL, INDEX idx_activity_created (created_at), INDEX idx_activity_action_user (action, user_id, created_at), INDEX idx_activity_action_ip (action, ip_address, created_at));
CREATE TABLE permissions (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, role ENUM('Super Admin','Admin') NOT NULL, module VARCHAR(80) NOT NULL, allowed BOOLEAN NOT NULL DEFAULT FALSE, UNIQUE KEY uq_permission_role_module (role, module));
CREATE TABLE settings (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, category VARCHAR(40) NOT NULL DEFAULT 'system', setting_key VARCHAR(100) NOT NULL UNIQUE, setting_value TEXT NOT NULL, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE file_events (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, event_uid CHAR(36) NOT NULL UNIQUE, computer_id INT UNSIGNED NOT NULL, event_type ENUM('created','modified','renamed','deleted') NOT NULL, file_name VARCHAR(255) NOT NULL, file_path VARCHAR(1024) NOT NULL, previous_path VARCHAR(1024) NULL, file_size BIGINT UNSIGNED NULL, sha256 CHAR(64) NULL, status ENUM('New','Reviewed','Scan Requested','Scanned','Scan Failed') NOT NULL DEFAULT 'New', detected_at DATETIME NOT NULL, received_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, risk_level ENUM('Unknown','Safe','Low','Medium','High','Critical','Failed') NOT NULL DEFAULT 'Unknown', suggested_confidential TINYINT(1) NOT NULL DEFAULT 0, classification ENUM('Normal','Confidential') NULL, scan_id INT UNSIGNED NULL, origin ENUM('local','browser_download','internet') NULL, download_url VARCHAR(500) NULL, CONSTRAINT fk_file_event_computer FOREIGN KEY (computer_id) REFERENCES computers(id) ON DELETE CASCADE, INDEX idx_file_events_computer_detected (computer_id, detected_at), INDEX idx_file_events_detected (detected_at));
ALTER TABLE scans ADD CONSTRAINT fk_scan_file_event FOREIGN KEY (file_event_id) REFERENCES file_events(id) ON DELETE SET NULL;
ALTER TABLE file_events ADD CONSTRAINT fk_file_event_scan FOREIGN KEY (scan_id) REFERENCES scans(id) ON DELETE SET NULL;
CREATE TABLE hash_blocklist (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, sha256 CHAR(64) NOT NULL UNIQUE, name VARCHAR(160) NOT NULL, severity ENUM('CRITICAL','HIGH','MEDIUM','LOW') NOT NULL DEFAULT 'HIGH', source VARCHAR(80) NOT NULL DEFAULT 'Manual', created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE hash_reputation (sha256 CHAR(64) NOT NULL PRIMARY KEY, source VARCHAR(40) NOT NULL DEFAULT 'VirusTotal', status ENUM('found','not_found') NOT NULL, malicious SMALLINT UNSIGNED NOT NULL DEFAULT 0, suspicious SMALLINT UNSIGNED NOT NULL DEFAULT 0, harmless SMALLINT UNSIGNED NOT NULL DEFAULT 0, undetected SMALLINT UNSIGNED NOT NULL DEFAULT 0, total SMALLINT UNSIGNED NOT NULL DEFAULT 0, name VARCHAR(160) NULL, checked_at DATETIME NOT NULL);
ALTER TABLE threats ADD CONSTRAINT fk_threat_scan FOREIGN KEY (scan_id) REFERENCES scans(id) ON DELETE SET NULL;
CREATE TABLE quarantine_items (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, computer_id INT UNSIGNED NOT NULL, file_event_id BIGINT UNSIGNED NULL, scan_id INT UNSIGNED NULL, file_name VARCHAR(255) NOT NULL, original_path VARCHAR(1024) NOT NULL, sha256 CHAR(64) NOT NULL, quarantine_name VARCHAR(160) NULL, status ENUM('Quarantine Requested','Quarantined','Release Requested','Released','Delete Requested','Deleted','Failed') NOT NULL, pending_action ENUM('quarantine','release','delete') NULL, action_sent_at DATETIME NULL, last_error VARCHAR(255) NULL, requested_by INT UNSIGNED NULL, release_reason VARCHAR(255) NULL, quarantined_at DATETIME NULL, released_at DATETIME NULL, deleted_at DATETIME NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, CONSTRAINT fk_quarantine_computer FOREIGN KEY (computer_id) REFERENCES computers(id) ON DELETE CASCADE, CONSTRAINT fk_quarantine_file_event FOREIGN KEY (file_event_id) REFERENCES file_events(id) ON DELETE SET NULL, CONSTRAINT fk_quarantine_scan FOREIGN KEY (scan_id) REFERENCES scans(id) ON DELETE SET NULL, CONSTRAINT fk_quarantine_user FOREIGN KEY (requested_by) REFERENCES users(id) ON DELETE SET NULL, INDEX idx_quarantine_jobs (computer_id, pending_action), INDEX idx_quarantine_status (status));
